import { initializeApp, cert } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { readFileSync } from 'fs';

const sa = JSON.parse(readFileSync('/data/.openclaw/workspace/.firebase-sa-sciquest.json', 'utf8'));
initializeApp({ credential: cert(sa) });
const db = getFirestore();

// Borrar colección existente
const existing = await db.collection('theory').get();
const deletePromises = existing.docs.map(d => d.ref.delete());
await Promise.all(deletePromises);
console.log(`🗑️  Deleted ${existing.docs.length} existing cards`);

const cards = [
  // ─── CHEMISTRY ─────────────────────────────────────────────────────
  {
    subject: 'chemistry', order: 1, difficulty: 'beginner',
    gradient: 'from-emerald-600 to-teal-500', emoji: '🧪',
    title: 'La Tabla Periódica',
    tagline: 'El mapa del universo químico',
    body: 'La tabla periódica organiza los 118 elementos conocidos en filas (períodos) y columnas (grupos) según su número atómico y propiedades. Dmitri Mendeleev la creó en 1869 y fue tan acertada que predijo elementos que aún no se habían descubierto, incluyendo sus propiedades. Cada casilla muestra el símbolo, número atómico (protones) y masa atómica del elemento. Los elementos en la misma columna comparten propiedades químicas similares porque tienen el mismo número de electrones en su capa exterior.',
    keyPoints: ['Filas = períodos (misma cantidad de capas electrónicas)', 'Columnas = grupos (mismas propiedades químicas)', 'Los metales están a la izquierda, no metales a la derecha', 'El número atómico = número de protones en el núcleo'],
    visual: '1H → 2He\n3Li 4Be ... 5B 6C 7N 8O 9F 10Ne\n(cada fila añade una capa electrónica)',
    funFact: 'Mendeleev dejó espacios en blanco para elementos no descubiertos. Predijo el Galio (1871) con tal precisión que cuando se descubrió en 1875 su masa era casi exactamente la que él había calculado.',
  },
  {
    subject: 'chemistry', order: 2, difficulty: 'beginner',
    gradient: 'from-teal-600 to-emerald-400', emoji: '⚛️',
    title: 'El Átomo',
    tagline: 'Casi todo es vacío',
    body: 'El átomo es la unidad fundamental de la materia y está formado por un núcleo central (protones y neutrones) rodeado de electrones en órbita. Lo más sorprendente es que el átomo es prácticamente vacío: si el núcleo fuera una naranja en el centro de un estadio de fútbol, los electrones estarían girando en las gradas. Los protones tienen carga positiva, los neutrones son neutros, y los electrones tienen carga negativa. El número de protones define qué elemento es (1=hidrógeno, 6=carbono, 79=oro).',
    keyPoints: ['Protones (+) y neutrones (0) en el núcleo', 'Electrones (-) en capas orbitales alrededor', 'El átomo es 99.9999% espacio vacío', 'Número atómico = número de protones = número de electrones (átomo neutro)'],
    visual: '    e⁻ ⬤\n  ⬤ [p⁺n⁰] ⬤\n    e⁻ ⬤',
    funFact: 'Si pudieras eliminar todo el espacio vacío de los átomos que forman a todos los humanos de la Tierra, el total de materia cabría en un cubo de menos de 1 km de lado.',
  },
  {
    subject: 'chemistry', order: 3, difficulty: 'intermediate',
    gradient: 'from-emerald-600 to-teal-500', emoji: '🧂',
    title: 'Enlace Iónico',
    tagline: 'Robo de electrones entre átomos',
    body: 'El enlace iónico ocurre cuando un átomo cede uno o más electrones a otro, formando iones con cargas opuestas que se atraen. Los metales suelen perder electrones (se convierten en cationes con carga +) y los no metales los ganan (se convierten en aniones con carga -). La sal de mesa (NaCl) es el ejemplo más famoso: el sodio cede un electrón al cloro, formando Na⁺ y Cl⁻ que se atraen mutuamente. Los compuestos iónicos forman redes cristalinas ordenadas y tienen puntos de fusión elevados.',
    keyPoints: ['Metal + No metal = enlace iónico', 'Se forman iones con cargas opuestas que se atraen', 'NaCl: Na pierde 1e⁻ → Na⁺, Cl gana 1e⁻ → Cl⁻', 'Sólidos a temperatura ambiente, alto punto de fusión', 'Conducen electricidad cuando están disueltos en agua'],
    formula: 'Na → Na⁺ + e⁻\nCl + e⁻ → Cl⁻\nNa⁺ + Cl⁻ → NaCl',
    formulaDesc: 'El sodio cede su electrón al cloro formando sal',
    funFact: 'La atracción iónica es tan fuerte que hay que calentar la sal común a 801°C para fundirla. Sin embargo, disuelta en agua conduce perfectamente la electricidad porque los iones quedan libres para moverse.',
  },
  {
    subject: 'chemistry', order: 4, difficulty: 'intermediate',
    gradient: 'from-green-600 to-teal-500', emoji: '💧',
    title: 'Enlace Covalente',
    tagline: 'Compartiendo electrones para vivir',
    body: 'En el enlace covalente dos átomos comparten electrones para completar sus capas exteriores sin que ninguno los ceda totalmente. Es el tipo de enlace que mantiene unidas las moléculas orgánicas y la mayoría de los compuestos de la vida. El agua (H₂O) es un ejemplo perfecto: el oxígeno comparte un electrón con cada hidrógeno. Si los electrones se comparten desigualmente (como en el agua), el enlace es polar y la molécula tiene zonas con carga parcial positiva y negativa.',
    keyPoints: ['Los átomos comparten electrones (nadie los cede del todo)', 'H₂O: O comparte 1e⁻ con cada H', 'Enlace polar: los electrones se comparten desigualmente', 'La polaridad del agua permite la vida tal como la conocemos', 'Doble enlace (C=C) y triple enlace (N≡N) también existen'],
    formula: 'H· + ·H → H:H (H₂)\nO: + 2H → H:O:H (H₂O)',
    formulaDesc: 'Los puntos representan electrones compartidos',
    funFact: 'La polaridad del agua hace que las moléculas se atraigan entre sí (puentes de hidrógeno). Por eso el hielo flota sobre el agua líquida — el único compuesto común donde el sólido es menos denso que el líquido, permitiendo la vida bajo el hielo en invierno.',
  },
  {
    subject: 'chemistry', order: 5, difficulty: 'intermediate',
    gradient: 'from-emerald-600 to-teal-500', emoji: '🔥',
    title: 'Reacciones Químicas',
    tagline: 'Nada se crea, nada se destruye',
    body: 'Una reacción química ocurre cuando las sustancias se transforman rompiendo y formando nuevos enlaces, pero los átomos siempre se conservan. Los reactivos se convierten en productos, pero la cantidad total de cada tipo de átomo es siempre la misma (Ley de conservación de la masa). Las reacciones pueden ser exotérmicas (liberan calor, como la combustión) o endotérmicas (absorben calor, como la fotosíntesis). La velocidad de una reacción depende de la temperatura, concentración y presencia de catalizadores.',
    keyPoints: ['Reactivos → Productos (los átomos se conservan)', 'Exotérmica: libera energía (combustión, oxidación)', 'Endotérmica: absorbe energía (fotosíntesis, cocinar)', 'La ecuación química debe estar balanceada', 'Catalizadores aceleran la reacción sin consumirse'],
    formula: '2H₂ + O₂ → 2H₂O',
    formulaDesc: 'La combustión del hidrógeno: 4H + 2O → 2 moléculas de agua',
    funFact: 'Tu cuerpo realiza miles de reacciones químicas por segundo. La hemoglobina hace una reacción química para atrapar el oxígeno en los pulmones y soltarlo en los tejidos, millones de veces durante tu vida.',
  },
  {
    subject: 'chemistry', order: 6, difficulty: 'intermediate',
    gradient: 'from-teal-600 to-cyan-500', emoji: '🍋',
    title: 'Ácidos y Bases',
    tagline: 'La escala del pH, de 0 a 14',
    body: 'Los ácidos liberan iones H⁺ en solución acuosa y tienen pH inferior a 7, mientras que las bases liberan iones OH⁻ y tienen pH superior a 7. El agua pura tiene pH exactamente 7 (neutro). La escala pH es logarítmica: un cambio de 1 unidad representa un cambio de 10 veces en la concentración de iones H⁺. El vinagre tiene pH ≈ 3, el limón ≈ 2, el jabón ≈ 9. Cuando un ácido y una base se mezclan en proporciones correctas, se neutralizan formando agua y una sal.',
    keyPoints: ['pH < 7 = ácido, pH > 7 = base, pH = 7 = neutro', 'La escala es logarítmica: pH 3 es 10x más ácido que pH 4', 'Tu sangre mantiene pH 7.4 con extrema precisión', 'Ácido + Base → Sal + Agua (neutralización)', 'Indicadores como la col lombarda cambian de color según el pH'],
    formula: 'pH = -log[H⁺]',
    formulaDesc: 'El pH es el logaritmo negativo de la concentración de iones hidrógeno',
    funFact: 'Tu estómago tiene ácido clorhídrico (HCl) con pH ≈ 1.5-3.5, lo suficientemente ácido para disolver metales. El recubrimiento mucoso se regenera completamente cada 2 semanas para protegerse de su propio ácido.',
  },
  {
    subject: 'chemistry', order: 7, difficulty: 'beginner',
    gradient: 'from-emerald-600 to-teal-500', emoji: '🌡️',
    title: 'Estados de la Materia',
    tagline: 'Sólido, líquido, gas... y más',
    body: 'La materia puede existir en cuatro estados principales: sólido (estructura rígida), líquido (volumen definido pero forma adaptable), gas (sin forma ni volumen fijo) y plasma (gas ionizado a altísima temperatura, el estado más abundante del universo). Los cambios de estado ocurren cuando añadimos o quitamos energía. La temperatura a la que una sustancia pasa de sólido a líquido es su punto de fusión, y de líquido a gas es su punto de ebullición.',
    keyPoints: ['Sólido: estructura rígida, partículas muy juntas', 'Líquido: forma adaptable, partículas próximas pero móviles', 'Gas: partículas muy separadas y en movimiento libre', 'Plasma: el estado más común en el universo (estrellas, relámpagos)', 'El cambio de estado no cambia la composición química'],
    visual: '🧊 SÓLIDO →(fusión)→ 💧 LÍQUIDO →(evaporación)→ 💨 GAS\n         ←(solidificación)←     ←(condensación)←',
    funFact: 'El 99.9% de la materia visible del universo está en estado de plasma. Las estrellas, incluyendo el Sol, son enormes bolas de plasma. El estado sólido, que nos parece el más "normal", es excepcional en la escala cósmica.',
  },
  {
    subject: 'chemistry', order: 8, difficulty: 'intermediate',
    gradient: 'from-green-600 to-emerald-500', emoji: '🦠',
    title: 'Química Orgánica',
    tagline: 'El carbono como base de la vida',
    body: 'La química orgánica estudia los compuestos del carbono, y hay más de 10 millones de compuestos orgánicos conocidos, más que todos los compuestos inorgánicos juntos. El carbono es único porque puede formar 4 enlaces covalentes y unirse a sí mismo en cadenas, anillos y estructuras tridimensionales complejas. Los hidrocarburos (C+H) son los más simples: metano (CH₄), etano (C₂H₆), propano (C₃H₈). La bioquímica es química orgánica: proteínas, ADN, lípidos y carbohidratos son todos compuestos de carbono.',
    keyPoints: ['El carbono puede hacer 4 enlaces (tetravalente)', 'Cadenas de C-C pueden ser lineales, ramificadas o cíclicas', 'Hidrocarburos: solo C y H (gasolina, gas natural)', 'Los seres vivos están hechos de compuestos orgánicos', 'El petróleo es materia orgánica transformada por millones de años'],
    formula: 'CH₄ → C₂H₆ → C₃H₈ → C₄H₁₀...',
    formulaDesc: 'Serie homóloga de alcanos: metano, etano, propano, butano...',
    funFact: 'El diamante y el grafito (mina del lápiz) son ambos carbono puro, pero con estructuras completamente distintas. El diamante tiene carbono en estructura tetraédrica 3D (durísimo) y el grafito en capas planas 2D (resbaladizo). La misma molécula, propiedades opuestas.',
  },
  {
    subject: 'chemistry', order: 9, difficulty: 'advanced',
    gradient: 'from-teal-600 to-emerald-400', emoji: '⚡',
    title: 'Oxidación-Reducción (Redox)',
    tagline: 'El intercambio de electrones',
    body: 'Las reacciones redox implican transferencia de electrones entre sustancias: la oxidación es la pérdida de electrones y la reducción es la ganancia. El hierro se oxida (pierde electrones) cuando forma óxido de hierro (herrumbre), y el oxígeno se reduce (gana esos electrones). La combustión es también una reacción redox. Las baterías funcionan usando reacciones redox controladas para generar corriente eléctrica.',
    keyPoints: ['Oxidación = pérdida de electrones (OIL: Oxidation Is Loss)', 'Reducción = ganancia de electrones (RIG: Reduction Is Gain)', 'Siempre ocurren juntas: si algo se oxida, algo se reduce', 'La herrumbre: 4Fe + 3O₂ → 2Fe₂O₃', 'Las baterías convierten energía química redox en eléctrica'],
    formula: 'Fe → Fe²⁺ + 2e⁻ (oxidación)\nO₂ + 4e⁻ → 2O²⁻ (reducción)',
    formulaDesc: 'El hierro pierde electrones, el oxígeno los gana → herrumbre',
    funFact: 'Tu cuerpo usa reacciones redox en la mitocondria para extraer energía de la glucosa. La cadena de transporte de electrones genera 36-38 moléculas de ATP por cada molécula de glucosa oxidada.',
  },
  {
    subject: 'chemistry', order: 10, difficulty: 'advanced',
    gradient: 'from-emerald-600 to-teal-500', emoji: '🔬',
    title: 'Catalizadores y Enzimas',
    tagline: 'Acelerar sin consumirse',
    body: 'Un catalizador es una sustancia que acelera una reacción química sin ser consumida en el proceso, reduciendo la energía de activación. Los catalizadores industriales permiten fabricar fertilizantes (proceso Haber-Bosch), refinar petróleo y producir plásticos. Las enzimas son catalizadores biológicos (proteínas) que permiten que las reacciones del metabolismo ocurran a temperatura corporal: sin ellas, muchas reacciones tardarían millones de años.',
    keyPoints: ['Reducen la energía de activación sin consumirse', 'No cambian el equilibrio de la reacción, solo la velocidad', 'Los catalizadores industriales salvan millones de vidas (fertilizantes)', 'Las enzimas son catalizadores biológicos ultraespecíficos', 'La temperatura y el pH afectan la actividad enzimática'],
    visual: 'SIN catalizador:  ⛰️⛰️⛰️ (mucha energía)\nCON catalizador:  🏔️   (menos energía)\nProductos:        ✅   (igual resultado)',
    funFact: 'La enzima catalasa puede descomponer 40 millones de moléculas de agua oxigenada por segundo. Es una de las enzimas más rápidas conocidas. Por eso cuando pones agua oxigenada en una herida burbujea tan rápido.',
  },

  // ─── QUANTUM ───────────────────────────────────────────────────────
  {
    subject: 'quantum', order: 1, difficulty: 'intermediate',
    gradient: 'from-indigo-600 to-purple-500', emoji: '🌀',
    title: 'Superposición Cuántica',
    tagline: 'Ser dos cosas a la vez hasta que mires',
    body: 'En el mundo cuántico, una partícula puede existir en múltiples estados simultáneamente hasta que es observada o medida. Cuando medimos, la función de onda "colapsa" y la partícula adopta un estado definido. Imagina una moneda girando en el aire: no es ni cara ni cruz hasta que la paras. Esto no es una metáfora de nuestra ignorancia, es la realidad fundamental del universo: la partícula genuinamente no tiene un estado definido hasta que se mide.',
    keyPoints: ['Una partícula puede estar en múltiples estados a la vez', 'La medición colapsa la superposición a un estado definido', 'No es incertidumbre de nuestro conocimiento: es real', 'El gato de Schrödinger ilustra lo absurdo en escala macroscópica', 'Los qubits en computación cuántica explotan la superposición'],
    visual: 'MONEDA GIRANDO:\n🪙 → 🌀 (superposición) → 😊 ó 😢 (al mirar)',
    funFact: 'El gato de Schrödinger (1935) fue diseñado por el propio Schrödinger para mostrar lo absurdo de la mecánica cuántica a escala macroscópica: un gato en una caja conectado a un decaimiento radiactivo estaría vivo Y muerto simultáneamente hasta que abrieras la caja.',
  },
  {
    subject: 'quantum', order: 2, difficulty: 'advanced',
    gradient: 'from-purple-600 to-indigo-500', emoji: '🔗',
    title: 'Entrelazamiento Cuántico',
    tagline: 'Dos partículas conectadas al instante',
    body: 'El entrelazamiento cuántico ocurre cuando dos partículas quedan conectadas de tal manera que el estado de una determina instantáneamente el estado de la otra, sin importar la distancia que las separe. Einstein lo llamó "acción fantasmal a distancia" y pensaba que era imposible (paradoja EPR, 1935). Pero los experimentos de Bell (1964) demostraron que el entrelazamiento es real.',
    keyPoints: ['Dos partículas entrelazadas comparten estado cuántico', 'Medir una afecta instantáneamente a la otra', 'No viola la relatividad: no permite transmitir información más rápido que la luz', 'Einstein creía que era imposible (estaba equivocado)', 'Base de la criptografía cuántica y la computación cuántica'],
    visual: '⚛️A ←── entrelazadas ──→ ⚛️B\nMedir A = ↑  →  B mide = ↓\n(aunque estén a 1000 km)',
    funFact: 'En 2017, científicos chinos demostraron entrelazamiento cuántico entre partículas separadas 1.203 km usando el satélite Micius. Se está trabajando en una internet cuántica basada en entrelazamiento.',
  },
  {
    subject: 'quantum', order: 3, difficulty: 'advanced',
    gradient: 'from-indigo-600 to-purple-500', emoji: '🚇',
    title: 'Efecto Túnel Cuántico',
    tagline: 'Atravesar paredes... literalmente',
    body: 'El efecto túnel es uno de los fenómenos más extraños de la mecánica cuántica: una partícula puede "atravesar" una barrera de energía que clásicamente sería infranqueable. Esto ocurre porque las partículas cuánticas se describen como funciones de onda que se extienden en el espacio, y hay una pequeña pero no nula probabilidad de encontrar la partícula al otro lado de la barrera.',
    keyPoints: ['Las partículas tienen probabilidad de aparecer al otro lado de una barrera', 'Más probable con barreras delgadas o partículas ligeras', 'El sol funciona gracias al efecto túnel (fusión nuclear)', 'Tu memoria USB usa efecto túnel para almacenar bits', 'Los microscopios STM permiten ver átomos individuales'],
    visual: '→→→ [BARRERA CLÁSICA]\n→→→ ≈≈≈ ... ≈≈≈ →\n Resultado: partícula aparece al otro lado',
    funFact: 'Sin el efecto túnel, el Sol no brillaría. La temperatura del núcleo solar (15 millones de °C) es insuficiente para que los protones superen su repulsión clásicamente. El efecto túnel permite la fusión de todas formas.',
  },
  {
    subject: 'quantum', order: 4, difficulty: 'intermediate',
    gradient: 'from-violet-600 to-indigo-500', emoji: '〰️',
    title: 'Dualidad Onda-Partícula',
    tagline: 'Ola y pelota a la vez',
    body: 'La dualidad onda-partícula es uno de los pilares de la mecánica cuántica: los electrones, fotones y demás partículas se comportan como ondas o como partículas dependiendo de cómo las observamos. En el experimento de la doble rendija, un electrón pasa por dos rendijas simultáneamente y crea un patrón de interferencia, pero si intentas detectar por cuál rendija pasó, el patrón desaparece.',
    keyPoints: ['Los fotones y electrones se comportan como ondas Y como partículas', 'Experimento doble rendija: la observación cambia el resultado', 'De Broglie: λ = h/mv (toda materia tiene longitud de onda)', 'A escala humana la longitud de onda es indetectable', 'Esto no es fallo de instrumentos: la naturaleza es así'],
    formula: 'λ = h / (m × v)',
    formulaDesc: 'Longitud de onda de De Broglie: h = constante de Planck, m = masa, v = velocidad',
    funFact: 'Incluso un balón de fútbol tiene longitud de onda cuántica: ~10⁻³⁴ metros, un billón de veces más pequeño que un protón. Por eso el efecto cuántico es indetectable a nuestro nivel, pero existe.',
  },
  {
    subject: 'quantum', order: 5, difficulty: 'advanced',
    gradient: 'from-indigo-600 to-purple-500', emoji: '❓',
    title: 'Principio de Incertidumbre',
    tagline: 'No puedes saber todo a la vez',
    body: 'El principio de incertidumbre de Heisenberg (1927) establece que cuanto más exactamente conoces la posición de una partícula (Δx), menos puedes saber sobre su cantidad de movimiento (Δp), y viceversa. Esta no es una limitación tecnológica: es una propiedad fundamental del universo. Para medir la posición necesitas interactuar con la partícula, y esa interacción perturba el momento.',
    keyPoints: ['Δx · Δp ≥ ℏ/2 (posición × momento ≥ constante)', 'No es imprecisión de instrumentos: es límite fundamental', 'También aplica a energía-tiempo: ΔE · Δt ≥ ℏ/2', 'Permite que partículas "pidan prestada" energía brevemente', 'Explica por qué los electrones no caen al núcleo atómico'],
    formula: 'Δx · Δp ≥ ℏ/2',
    formulaDesc: 'ℏ = h/(2π) ≈ 1.055×10⁻³⁴ J·s (constante de Planck reducida)',
    funFact: 'El principio de incertidumbre explica por qué el universo no está vacío: el vacío tiene fluctuaciones cuánticas donde pares partícula-antipartícula aparecen y desaparecen. El efecto Casimir lo demostró experimentalmente con dos placas metálicas muy juntas.',
  },
  {
    subject: 'quantum', order: 6, difficulty: 'advanced',
    gradient: 'from-purple-600 to-violet-500', emoji: '🌊',
    title: 'Función de Onda y Schrödinger',
    tagline: 'La ecuación que describe la realidad',
    body: 'La función de onda (ψ) describe todo lo que se puede saber sobre el estado cuántico de una partícula. No nos dice dónde está la partícula, sino la probabilidad de encontrarla en cada punto del espacio: la probabilidad es proporcional a |ψ|². La ecuación de Schrödinger (1926) describe cómo evoluciona ψ en el tiempo. Los orbitales atómicos (s, p, d, f) son representaciones gráficas de |ψ|².',
    keyPoints: ['|ψ|² = probabilidad de encontrar la partícula en ese punto', 'La ecuación de Schrödinger es determinista', 'El colapso de la función de onda al medir introduce el azar', 'Los orbitales atómicos son nubes de probabilidad', 'La superposición = la partícula está en todos los estados posibles de ψ'],
    formula: 'iℏ ∂ψ/∂t = Ĥψ',
    formulaDesc: 'Ecuación de Schrödinger: iℏ × variación temporal = operador hamiltoniano × ψ',
    funFact: 'El electrón del átomo de hidrógeno no orbita el núcleo como un planeta. Existe como una nube de probabilidad esférica: hay 90% de probabilidad de encontrarlo dentro de una esfera de radio 0.053 nm, pero técnicamente también hay probabilidad de encontrarlo en el Sol.',
  },
  {
    subject: 'quantum', order: 7, difficulty: 'advanced',
    gradient: 'from-indigo-600 to-purple-500', emoji: '💻',
    title: 'Computación Cuántica',
    tagline: 'El ordenador del futuro (ya presente)',
    body: 'Los ordenadores cuánticos usan qubits en lugar de bits clásicos. Un qubit puede ser 0, 1, o superposición de ambos simultáneamente. Con n qubits puedes procesar 2ⁿ estados en paralelo. Para ciertos problemas (factorización, simulación molecular, optimización), los ordenadores cuánticos tienen ventaja exponencial sobre los clásicos.',
    keyPoints: ['Qubit: puede ser 0, 1, o superposición de ambos', 'n qubits = 2ⁿ estados en paralelo (exponencial)', 'Algoritmo de Shor: factoriza números rompiendo RSA', 'Algoritmo de Grover: búsqueda en tiempo √N en lugar de N', 'Error cuántico: principal obstáculo actual (qubits muy frágiles)'],
    visual: 'Clásico:  [0] ó [1]\nCuántico: [0] + [1] simultáneamente\n→ 50 qubits = 2⁵⁰ ≈ 1 billón de estados a la vez',
    funFact: 'En 2019, el procesador Sycamore de Google (53 qubits) realizó en 200 segundos un cálculo que tomaría 10.000 años al supercomputador Summit. En 2023, IBM anunció un procesador de 1.121 qubits.',
  },
  {
    subject: 'quantum', order: 8, difficulty: 'intermediate',
    gradient: 'from-violet-600 to-purple-500', emoji: '🔬',
    title: 'El Experimento de la Doble Rendija',
    tagline: 'El experimento más desconcertante de la física',
    body: 'Cuando disparas electrones uno a uno hacia una pared con dos rendijas, esperarías que cada electrón pasara por una rendija y formara dos bandas. En cambio, se forma un patrón de interferencia como si cada electrón pasara por las dos rendijas simultáneamente. Lo más perturbador: si colocas un detector para saber por cuál rendija pasa, el patrón de interferencia desaparece. El acto de observar cambia el resultado.',
    keyPoints: ['Sin detector: patrón de interferencia (comportamiento onda)', 'Con detector: dos bandas (comportamiento partícula)', 'Cada electrón individual interfiere consigo mismo', 'La observación colapsa la superposición', 'Funciona incluso con moléculas grandes'],
    visual: 'SIN detector:\nElectrón → [rendija 1]  → ⋮⋮⋮⋮ patrón\n           [rendija 2]  → interferencia\n\nCON detector:\nElectrón → [rendija 1] → ●● (solo dos bandas)',
    funFact: 'En 2019, el experimento se realizó con moléculas de hasta 2000 átomos y aun así mostraron patrón de interferencia. Nadie sabe exactamente dónde termina el reino cuántico y empieza el clásico.',
  },
  {
    subject: 'quantum', order: 9, difficulty: 'advanced',
    gradient: 'from-indigo-600 to-purple-500', emoji: '🎯',
    title: 'Números Cuánticos y Orbitales',
    tagline: 'La dirección de cada electrón',
    body: 'Los números cuánticos describen el estado de cada electrón en un átomo. El número principal (n) indica el nivel de energía. El azimutal (l) da la forma del orbital (s=esfera, p=doble lóbulo, d=más complejo). El magnético (ml) indica la orientación. El spin (ms = +½ o -½) es una propiedad intrínseca. El principio de exclusión de Pauli dice que ningún orbital puede tener dos electrones con todos los números cuánticos iguales.',
    keyPoints: ['n = nivel de energía (1, 2, 3...)', 'l = forma del orbital (s, p, d, f)', 'ml = orientación en el espacio', 'ms = spin del electrón (↑ o ↓)', 'Principio de Pauli: máximo 2 electrones por orbital (spin opuesto)'],
    visual: 'n=1: orbital 1s (esfera)\nn=2: 2s (esfera) + 2p (3 dobles lóbulos)\nn=3: 3s + 3p + 3d (5 orbitales complejos)',
    funFact: 'El principio de exclusión de Pauli es la razón por la que la materia es sólida. Si los electrones pudieran ocupar los mismos estados, toda la materia colapsaría. ¡El hecho de que puedas sentarte en una silla es mecánica cuántica!',
  },

  // ─── NUCLEAR ───────────────────────────────────────────────────────
  {
    subject: 'nuclear', order: 1, difficulty: 'beginner',
    gradient: 'from-amber-600 to-orange-500', emoji: '⚛️',
    title: 'Estructura del Núcleo Atómico',
    tagline: 'Un núcleo increíblemente denso',
    body: 'El núcleo atómico contiene protones (carga +) y neutrones (sin carga), juntos llamados nucleones. Aunque los protones se repelen entre sí por la fuerza electromagnética, están mantenidos juntos por la fuerza nuclear fuerte, la fuerza más poderosa de la naturaleza (100 veces más intensa que el electromagnetismo, pero de alcance muy corto). El núcleo es 100.000 veces más pequeño que el átomo completo.',
    keyPoints: ['Protones (+) y neutrones (0) = nucleones', 'La fuerza nuclear fuerte supera la repulsión electromagnética', 'La fuerza fuerte actúa solo a distancias muy cortas (~10⁻¹⁵ m)', 'El núcleo es 100.000 veces más pequeño que el átomo', 'La densidad nuclear es ~10¹⁷ kg/m³ (inimaginablemente densa)'],
    visual: 'Átomo:  [nube de e⁻ ≈ 10⁻¹⁰ m]\nNúcleo: [p⁺n⁰ ≈ 10⁻¹⁵ m]\nEscala: núcleo=naranja → átomo=estadio de fútbol',
    funFact: 'Una cucharadita de materia nuclear (estrella de neutrones) pesa ~1.000 millones de toneladas. Las estrellas de neutrones son el estado final de estrellas grandes: todo el material del Sol comprimido en una esfera de 20 km de diámetro.',
  },
  {
    subject: 'nuclear', order: 2, difficulty: 'beginner',
    gradient: 'from-orange-600 to-amber-500', emoji: '☢️',
    title: 'Radiactividad Natural',
    tagline: 'Núcleos inestables que se transforman',
    body: 'La radiactividad es el proceso por el cual núcleos atómicos inestables se desintegran emitiendo partículas o energía para alcanzar un estado más estable. Fue descubierta accidentalmente por Henri Becquerel en 1896. Marie y Pierre Curie aislaron el radio y el polonio y acuñaron el término "radiactividad". La inestabilidad nuclear ocurre cuando hay demasiados o muy pocos neutrones respecto a protones.',
    keyPoints: ['Los núcleos inestables emiten radiación para estabilizarse', 'Henri Becquerel descubrió la radiactividad en 1896', 'Marie Curie estudió el uranio, radio y polonio (2 Nobel)', 'Tres tipos principales: alfa (α), beta (β), gamma (γ)', 'La radiactividad no puede activarse ni desactivarse: es espontánea'],
    visual: 'Núcleo inestable → emisión de radiación → núcleo más estable\n\n²³⁸U → ²³⁴Th + ⁴He (partícula α) + energía',
    funFact: 'Marie Curie fue la primera persona en ganar dos Premios Nobel (Física 1903, Química 1911). Murió en 1934 de anemia aplásica por exposición a la radiactividad. Sus cuadernos aún son tan radiactivos que se guardan en cajas de plomo.',
  },
  {
    subject: 'nuclear', order: 3, difficulty: 'intermediate',
    gradient: 'from-amber-600 to-orange-500', emoji: '🔴',
    title: 'Desintegración Alfa (α)',
    tagline: 'El núcleo expulsa una partícula grande',
    body: 'La desintegración alfa ocurre cuando un núcleo inestable expulsa una partícula alfa, idéntica a un núcleo de helio-4: 2 protones y 2 neutrones. Al emitir una partícula alfa, el número atómico decrece en 2 y el número másico en 4, transformando el elemento. Las partículas alfa son altamente ionizantes pero con muy baja penetración: se detienen con una hoja de papel.',
    keyPoints: ['Partícula alfa = núcleo de ⁴He (2 protones + 2 neutrones)', 'Número atómico -2, número másico -4', 'Alta ionización, baja penetración (para con papel)', 'Peligrosa si se inhala o ingiere', 'El Radio-226 emite alfas con vida media de 1.600 años'],
    formula: '²³⁸U → ²³⁴Th + ⁴He',
    formulaDesc: 'Uranio-238 se convierte en Torio-234 emitiendo una partícula alfa',
    funFact: 'Alexander Litvinenko fue asesinado en Londres en 2006 con Polonio-210, un emisor alfa puro. Técnicamente "seguro" desde fuera (no penetra la piel) pero letal cuando se ingiere: una millonésima de gramo fue suficiente para una dosis fatal.',
  },
  {
    subject: 'nuclear', order: 4, difficulty: 'intermediate',
    gradient: 'from-orange-600 to-amber-500', emoji: '⚡',
    title: 'Desintegración Beta (β)',
    tagline: 'Un neutrón se transforma en protón',
    body: 'En la desintegración beta-menos (β⁻), un neutrón del núcleo se transforma en un protón, emitiendo un electrón y un antineutrino. Esto aumenta el número atómico en 1 (el elemento cambia) pero el número másico permanece igual. Las partículas beta son más penetrantes que las alfa pero menos que los rayos gamma.',
    keyPoints: ['β⁻: n → p + e⁻ + antineutrino (número atómico +1)', 'β⁺: p → n + positrón + neutrino (número atómico -1)', 'Penetración media: para con aluminio delgado', 'El elemento cambia en la desintegración beta', 'El C-14 se desintegra beta: base de la datación radiocarbónica'],
    formula: '¹⁴C → ¹⁴N + e⁻ + ν̄ₑ',
    formulaDesc: 'Carbono-14 decae a Nitrógeno-14 emitiendo un electrón y un antineutrino',
    funFact: 'La desintegración beta llevó al descubrimiento del neutrino. Pauli propuso en 1930 que debía existir una partícula invisible. Nadie creyó que se pudiera detectar jamás, pero en 1956 se detectó directamente. Cada segundo pasan 65 billones de neutrinos por cada cm² de tu cuerpo.',
  },
  {
    subject: 'nuclear', order: 5, difficulty: 'intermediate',
    gradient: 'from-amber-600 to-orange-500', emoji: '🌊',
    title: 'Radiación Gamma (γ)',
    tagline: 'La radiación más penetrante',
    body: 'La radiación gamma consiste en fotones de altísima energía emitidos cuando un núcleo pasa de un estado excitado a uno de menor energía. A diferencia de alfa y beta, la gamma no cambia el número de protones ni neutrones. Los rayos gamma tienen la mayor penetración: requieren varios centímetros de plomo o metros de hormigón para ser absorbidos.',
    keyPoints: ['Fotones de alta energía (como rayos X pero más energéticos)', 'No cambia el elemento (solo libera energía del núcleo excitado)', 'Máxima penetración: necesita plomo grueso o hormigón', 'Mínima ionización por unidad de trayectoria', 'Usado en medicina: radioterapia, esterilización, PET scan'],
    visual: 'α (alfa):  ████░░░░░░ (para: papel)\nβ (beta):  ████████░░ (para: aluminio)\nγ (gamma): ██████████ (para: plomo/hormigón)',
    funFact: 'Las explosiones de rayos gamma (GRB) son los eventos más energéticos del universo tras el Big Bang. Un GRB libera más energía en segundos que el Sol en 10.000 millones de años. Si uno ocurriera a 200 años luz, destruiría la capa de ozono de la cara expuesta.',
  },
  {
    subject: 'nuclear', order: 6, difficulty: 'advanced',
    gradient: 'from-orange-600 to-red-500', emoji: '💥',
    title: 'Fisión Nuclear',
    tagline: 'Rompiendo átomos para liberar energía',
    body: 'La fisión nuclear ocurre cuando un núcleo pesado (como Uranio-235) absorbe un neutrón y se divide en dos fragmentos más pequeños, liberando energía enorme y 2-3 neutrones adicionales. Estos neutrones pueden causar más fisiones en cadena. En una central nuclear, la reacción se controla con moderadores y barras de control. En una bomba atómica, la reacción se deja fuera de control.',
    keyPoints: ['U-235 + neutrón → Ba + Kr + 3 neutrones + energía', 'Los neutrones liberados causan más fisiones (reacción en cadena)', '1 kg de U-235 ≈ energía de 3 millones de kg de carbón', 'Masa crítica: mínima masa de combustible para reacción sostenida', 'Central nuclear: reacción controlada; bomba: reacción exponencial'],
    formula: '²³⁵U + n → ¹⁴¹Ba + ⁹²Kr + 3n + 200 MeV',
    formulaDesc: 'Un neutrón lento fisiona U-235 produciendo bario, kriptón, 3 neutrones y ~200 MeV',
    funFact: 'El primer reactor nuclear fue construido por Enrico Fermi debajo de las gradas de un estadio de squash en la Universidad de Chicago en 1942. El experimento tuvo éxito el 2 de diciembre de 1942: la primera reacción nuclear en cadena sostenida. No había escudos de radiación adecuados.',
  },
  {
    subject: 'nuclear', order: 7, difficulty: 'advanced',
    gradient: 'from-amber-600 to-orange-500', emoji: '🌟',
    title: 'Fusión Nuclear',
    tagline: 'La energía de las estrellas',
    body: 'La fusión nuclear es el proceso inverso a la fisión: dos núcleos ligeros se unen para formar uno más pesado, liberando cantidades colosales de energía según E=mc². Es el proceso que alimenta el Sol y todas las estrellas. La fusión es mucho más energética por unidad de masa que la fisión y no produce residuos radiactivos de larga vida.',
    keyPoints: ['H + H → He + energía (10x más que la fisión por kg)', 'Requiere temperaturas > 100 millones de °C para vencer la repulsión', 'El Sol fusiona 600 millones de toneladas de H por segundo', 'Sin residuos radiactivos de larga vida (combustible: agua de mar + litio)', 'ITER (Francia) es el mayor proyecto de fusión: objetivo 2035'],
    formula: '²H + ³H → ⁴He + n + 17.6 MeV',
    formulaDesc: 'Deuterio + Tritio → Helio + neutrón + 17.6 MeV (fusión controlada)',
    funFact: 'El Sol ha estado fusionando hidrógeno durante 4.600 millones de años y tiene combustible para otros 5.000 millones más. Cada segundo el Sol convierte 4 millones de toneladas de masa en pura energía (E=mc²).',
  },
  {
    subject: 'nuclear', order: 8, difficulty: 'intermediate',
    gradient: 'from-orange-600 to-amber-500', emoji: '⏱️',
    title: 'Vida Media Radiactiva',
    tagline: 'El reloj del universo',
    body: 'La vida media (semivida) es el tiempo que tarda la mitad de los átomos de una muestra radiactiva en desintegrarse. Es una característica fija de cada isótopo y no depende de la temperatura, presión ni composición química. Tras una vida media queda 1/2, tras dos 1/4, tras tres 1/8 (decaimiento exponencial).',
    keyPoints: ['Tras cada vida media, queda la mitad de la muestra', 'N(t) = N₀ × (1/2)^(t/t½)', 'C-14: 5.730 años → datación hasta 50.000 años', 'U-238: 4.500 millones de años → edad de la Tierra', 'Po-210: 138 días; I-131: 8 días (uso médico)'],
    formula: 'N(t) = N₀ × (½)^(t/t½)',
    formulaDesc: 'N(t) = cantidad restante, N₀ = inicial, t = tiempo, t½ = vida media',
    funFact: 'La datación por carbono-14 funciona porque los organismos vivos mantienen una proporción constante de C-14. Al morir, dejan de incorporar C-14 y el que tienen empieza a decaer. Se puede calcular cuándo murió el organismo con precisión de ±40 años para muestras de hasta 50.000 años.',
  },
  {
    subject: 'nuclear', order: 9, difficulty: 'intermediate',
    gradient: 'from-amber-600 to-orange-500', emoji: '🏥',
    title: 'Medicina Nuclear y Aplicaciones',
    tagline: 'La radiación que salva vidas',
    body: 'La medicina nuclear usa isótopos radiactivos para diagnóstico y tratamiento. En diagnóstico, se inyectan trazadores radiactivos que se acumulan en órganos específicos. La PET usa glucosa marcada con F-18 para detectar tumores. El I-131 trata el cáncer de tiroides porque la tiroides acumula el yodo naturalmente.',
    keyPoints: ['Tc-99m: diagnóstico general, vida media 6h (más usado)', 'PET scan: F-18-glucosa detecta tumores y actividad cerebral', 'I-131: tratamiento de cáncer de tiroides e hipertiroidismo', 'Radioterapia: haces de radiación apuntados a tumores', 'Esterilización: rayos gamma esterilizan material médico'],
    visual: 'PET SCAN:\nGlucosa-¹⁸F → paciente → β⁺ + γγ\n→ detectores → imagen 3D de actividad metabólica',
    funFact: 'El Tc-99m es el radioisótopo más usado en medicina nuclear: más de 30 millones de procedimientos al año en todo el mundo. Tiene vida media de 6 horas (suficiente para el diagnóstico, se desintegra antes de causar daño significativo).',
  },

  // ─── NEWTONIAN ─────────────────────────────────────────────────────
  {
    subject: 'newtonian', order: 1, difficulty: 'beginner',
    gradient: 'from-blue-600 to-cyan-500', emoji: '🛸',
    title: 'Primera Ley de Newton — Inercia',
    tagline: 'Un objeto que se mueve seguirá moviéndose',
    body: 'La primera ley de Newton establece que un objeto en reposo permanece en reposo y un objeto en movimiento continúa a velocidad constante en línea recta, a menos que una fuerza externa actúe sobre él. Antes de Newton, Aristóteles creía que los objetos naturalmente se detienen y necesitan una fuerza para moverse. En el espacio, una nave con los motores apagados continúa moviéndose indefinidamente.',
    keyPoints: ['Sin fuerza → sin cambio de movimiento (reposo o velocidad constante)', 'La masa es la medida de la inercia (más masa = más resistencia al cambio)', 'Galileo demostró la inercia experimentalmente antes que Newton', 'En el espacio no hay fricción: la inercia es perfecta', 'Los pasajeros se inclinan cuando el coche frena (inercia)'],
    visual: '🛸 (espacio, sin fuerzas) → 🛸 → 🛸 → 🛸 (velocidad constante)\n🚗 (frena) → pasajero se inclina hacia adelante',
    funFact: 'Las sondas Voyager 1 y 2, lanzadas en 1977, han viajado más de 23.000 millones de km con los motores prácticamente apagados desde hace décadas. La primera ley de Newton las mantiene en movimiento en el vacío del espacio interestelar.',
  },
  {
    subject: 'newtonian', order: 2, difficulty: 'beginner',
    gradient: 'from-cyan-600 to-blue-500', emoji: '💪',
    title: 'Segunda Ley de Newton — F = ma',
    tagline: 'La fuerza cambia el movimiento',
    body: 'La segunda ley de Newton es la más útil: la fuerza neta sobre un objeto es igual a su masa multiplicada por la aceleración que experimenta. Si aplicas el doble de fuerza, obtienes el doble de aceleración. Si tienes el doble de masa, necesitas el doble de fuerza para la misma aceleración. Esta ley permite calcular exactamente cómo se moverá cualquier objeto bajo la influencia de fuerzas conocidas.',
    keyPoints: ['F = m × a (fuerza = masa × aceleración)', 'La fuerza es un vector (tiene magnitud y dirección)', 'Se aplica a la fuerza NETA (suma de todas las fuerzas)', 'Más masa → menor aceleración para la misma fuerza', 'Unidad de fuerza: Newton (N) = kg·m/s²'],
    formula: 'F = m × a',
    formulaDesc: 'Fuerza neta (N) = Masa (kg) × Aceleración (m/s²)',
    funFact: 'Los cohetes del Saturno V producían 3.400 toneladas de empuje y tenían que acelerar 2.800 toneladas de masa. F=ma en su máxima expresión: en el primer segundo de vuelo, movían más material que cualquier máquina humana anterior.',
  },
  {
    subject: 'newtonian', order: 3, difficulty: 'beginner',
    gradient: 'from-blue-600 to-cyan-500', emoji: '🔄',
    title: 'Tercera Ley de Newton — Acción y Reacción',
    tagline: 'Toda acción tiene una reacción igual y opuesta',
    body: 'La tercera ley establece que para cada fuerza ejercida por un objeto sobre otro (acción), hay una fuerza igual en magnitud pero opuesta en dirección ejercida por el segundo sobre el primero (reacción). Los cohetes funcionan expulsando gas hacia abajo (acción) y el gas empuja el cohete hacia arriba (reacción). Cuando caminas, empujas el suelo hacia atrás y el suelo te empuja hacia adelante.',
    keyPoints: ['Acción y reacción son iguales en magnitud, opuestas en dirección', 'Siempre actúan sobre objetos DIFERENTES (no se cancelan)', 'Cohete: gases expulsados hacia abajo → cohete sube', 'Caminar: tu pie empuja el suelo → el suelo te empuja a ti', 'Si empujas a alguien, esa persona te empuja igual'],
    visual: 'COHETE:\n   🚀 ↑ (reacción)\n   ↓ 💨 (gases, acción)\n\nCOCHE:\n→ 🎾 → | (pelota empuja pared)\n        ← (pared empuja pelota)',
    funFact: 'Los calamares usan perfectamente la tercera ley: expulsan agua en una dirección y se mueven en la opuesta a velocidades de hasta 40 km/h. El cohete de agua o el globo soltado en el aire son demostraciones perfectas.',
  },
  {
    subject: 'newtonian', order: 4, difficulty: 'intermediate',
    gradient: 'from-cyan-600 to-blue-500', emoji: '🌍',
    title: 'Gravitación Universal',
    tagline: 'La fuerza que rige el cosmos',
    body: 'Newton formuló la Ley de Gravitación Universal: cada objeto con masa atrae a cualquier otro con masa, con una fuerza proporcional al producto de sus masas e inversamente proporcional al cuadrado de la distancia. Esta ley explica por qué cae una manzana, por qué la Luna orbita la Tierra, por qué la Tierra orbita el Sol, y por qué las galaxias se mantienen unidas.',
    keyPoints: ['F = G·m₁·m₂/r² (atracción entre masas)', 'A mayor distancia, menor fuerza (ley de cuadrado inverso)', 'La Luna "cae" hacia la Tierra pero su velocidad lateral la mantiene en órbita', 'Tu peso = m × g, donde g = 9.8 m/s² en superficie terrestre', 'La gravedad es la más débil de las 4 fuerzas fundamentales, pero de alcance infinito'],
    formula: 'F = G × m₁ × m₂ / r²',
    formulaDesc: 'G = 6.674×10⁻¹¹ N·m²/kg², r = distancia entre centros de masa',
    funFact: 'En la ISS (400 km de altitud), la gravedad es solo un 11% menor que en la superficie, pero los astronautas flotan porque están en caída libre continua alrededor de la Tierra. La órbita es básicamente caer hacia la Tierra pero ir tan rápido que siempre te "pierdes" el suelo.',
  },
  {
    subject: 'newtonian', order: 5, difficulty: 'intermediate',
    gradient: 'from-blue-600 to-cyan-500', emoji: '🚗',
    title: 'Energía Cinética',
    tagline: 'La energía del movimiento',
    body: 'La energía cinética es la energía que tiene un objeto debido a su movimiento. Depende de la masa y del cuadrado de la velocidad: duplicar la velocidad cuadruplica la energía cinética. Esto tiene consecuencias enormes en seguridad vial: un coche a 100 km/h tiene cuatro veces más energía cinética que el mismo coche a 50 km/h, y necesita cuatro veces más distancia de frenado.',
    keyPoints: ['Ec = ½ × m × v²', 'Duplicar la velocidad → 4x más energía cinética', 'La energía cinética se conserva en colisiones elásticas', 'En colisiones inelásticas parte se convierte en calor/sonido', 'Un tren de alta velocidad tiene la energía cinética de varias toneladas de TNT'],
    formula: 'Ec = ½ × m × v²',
    formulaDesc: 'm = masa (kg), v = velocidad (m/s), Ec = energía cinética (Joules)',
    funFact: 'Un peatón atropellado a 50 km/h tiene un 80% de probabilidad de morir. A 30 km/h, esa probabilidad baja al 10%. Duplicar la velocidad de 30 a 60 km/h no dobla la energía: la cuadruplica. Por eso las zonas de 30 km/h salvan vidas.',
  },
  {
    subject: 'newtonian', order: 6, difficulty: 'intermediate',
    gradient: 'from-cyan-600 to-blue-500', emoji: '🎢',
    title: 'Energía Potencial y Conservación',
    tagline: 'La energía guardada lista para usarse',
    body: 'La energía potencial es la energía almacenada en un objeto debido a su posición o estado. La más conocida es la energía potencial gravitatoria (Ep = mgh). En una montaña rusa, la energía se convierte constantemente entre potencial (en lo alto) y cinética (en lo bajo). El principio de conservación de la energía establece que la energía total de un sistema aislado permanece constante.',
    keyPoints: ['Ep = m × g × h (gravitatoria)', 'En ausencia de fricción: Ec + Ep = constante', 'Montaña rusa: potencial ↔ cinética continuamente', 'También existe Ep elástica (resorte), eléctrica, química', 'La fricción convierte energía mecánica en calor (irreversible)'],
    formula: 'Ep + Ec = constante\nm×g×h + ½×m×v² = E_total',
    formulaDesc: 'Sin fricción, la suma de energía potencial y cinética se conserva',
    funFact: 'Las presas de bombeo almacenan electricidad subiendo agua cuando hay exceso de energía y bajándola cuando hace falta. Son "baterías" de energía potencial gravitatoria de escala gigante. La presa de Bath County (EEUU) puede almacenar 24.000 MWh.',
  },
  {
    subject: 'newtonian', order: 7, difficulty: 'intermediate',
    gradient: 'from-blue-600 to-cyan-500', emoji: '🎱',
    title: 'Momento Lineal y Colisiones',
    tagline: 'La cantidad de movimiento se conserva siempre',
    body: 'El momento lineal (p) es el producto de la masa y la velocidad: p = m×v. La ley de conservación del momento establece que el momento total de un sistema aislado permanece constante, incluso durante colisiones. Las colisiones pueden ser elásticas (se conserva también Ec, como bolas de billar) o inelásticas (parte de Ec se convierte en calor/deformación).',
    keyPoints: ['p = m × v (momento lineal, kg·m/s)', 'El momento total se conserva en sistemas aislados', 'Colisión elástica: se conservan p y Ec (bolas de billar)', 'Colisión inelástica: se conserva p pero no Ec (choques de coches)', 'Impulso = F × Δt = cambio de momento (por eso los airbags alargan el impacto)'],
    formula: 'p = m × v\nm₁v₁ + m₂v₂ = m₁v₁\' + m₂v₂\'',
    formulaDesc: 'El momento total antes = momento total después de la colisión',
    funFact: 'Los airbags no reducen la fuerza del impacto directamente: reducen la desaceleración alargando el tiempo de la colisión. El impulso (F×t = cambio de momento) es fijo, pero al alargar t, F disminuye. La misma razón por la que los deportistas "siguen el movimiento" al atrapar una pelota.',
  },
  {
    subject: 'newtonian', order: 8, difficulty: 'intermediate',
    gradient: 'from-cyan-600 to-blue-500', emoji: '🌙',
    title: 'Movimiento Circular y Fuerza Centrípeta',
    tagline: 'Por qué la Luna no se cae',
    body: 'Un objeto que se mueve en círculo está constantemente acelerando hacia el centro del círculo, porque la dirección cambia continuamente. Esta aceleración centrípeta requiere una fuerza centrípeta apuntando siempre al centro. En el caso de la Luna, esta fuerza es la gravedad terrestre. Sin fuerza centrípeta, el objeto sale disparado en línea recta tangente al círculo.',
    keyPoints: ['Movimiento circular = aceleración constante hacia el centro', 'a_c = v²/r (aceleración centrípeta)', 'F_c = m×v²/r (fuerza centrípeta necesaria)', 'La Luna orbita porque la gravedad actúa como fuerza centrípeta', 'Sin fuerza centrípeta → el objeto sigue en línea recta (inercia)'],
    formula: 'F_c = m × v² / r',
    formulaDesc: 'm = masa, v = velocidad, r = radio de la trayectoria circular',
    funFact: 'La Luna se aleja de la Tierra ~3.8 cm por año: las mareas transfieren momento angular de la Tierra a la Luna. La Tierra frena su rotación (~1.4 ms por siglo) y la Luna gana radio orbital. Hace 1.400 millones de años, un día duraba solo 18 horas.',
  },
  {
    subject: 'newtonian', order: 9, difficulty: 'intermediate',
    gradient: 'from-blue-600 to-cyan-500', emoji: '🏹',
    title: 'Movimiento Proyectil',
    tagline: 'La parábola perfecta',
    body: 'El movimiento de un proyectil puede descomponerse en dos movimientos independientes: horizontal (velocidad constante) y vertical (caída libre, con aceleración g = 9.8 m/s²). La trayectoria resultante es una parábola. El ángulo óptimo para maximizar el alcance horizontal (ignorando el aire) es exactamente 45°.',
    keyPoints: ['Horizontal: velocidad constante (sin rozamiento)', 'Vertical: aceleración constante g = 9.8 m/s² hacia abajo', 'Ambos movimientos son independientes entre sí', 'Ángulo 45° = máximo alcance horizontal', 'El tiempo de vuelo depende solo del componente vertical'],
    formula: 'x = v₀cos(θ)·t\ny = v₀sin(θ)·t - ½·g·t²',
    formulaDesc: 'Componentes horizontal (x) y vertical (y) del movimiento proyectil',
    funFact: 'Galileo fue el primero en analizar el movimiento proyectil correctamente (~1590). Antes de él, se creía que los proyectiles seguían una línea recta y luego caían verticalmente. Galileo demostró la parábola matemáticamente y experimentalmente.',
  },
  {
    subject: 'newtonian', order: 10, difficulty: 'beginner',
    gradient: 'from-cyan-600 to-blue-500', emoji: '🔊',
    title: 'Ondas Mecánicas y Sonido',
    tagline: 'Vibración que viaja por la materia',
    body: 'Las ondas mecánicas son perturbaciones que se propagan a través de un medio material transfiriendo energía sin transportar materia. Las ondas transversales vibran perpendiculares a la dirección de propagación; las longitudinales (como el sonido) vibran paralelas. El sonido viaja a ~343 m/s en el aire (20°C), más rápido en líquidos y sólidos.',
    keyPoints: ['Ondas transversales: vibración perpendicular al movimiento', 'Ondas longitudinales: vibración paralela (sonido)', 'Velocidad del sonido: 343 m/s (aire), 1.500 m/s (agua), 5.000 m/s (acero)', 'Frecuencia (Hz) = tono; Amplitud = volumen', 'Efecto Doppler: la frecuencia cambia si la fuente se mueve'],
    formula: 'v = f × λ',
    formulaDesc: 'Velocidad de onda (m/s) = frecuencia (Hz) × longitud de onda (m)',
    funFact: 'Los terremotos generan tres tipos de ondas: P (longitudinales, más rápidas), S (transversales) y L (superficiales, más destructivas). Las P viajan a 6-7 km/s y pueden detectarse en el lado opuesto de la Tierra en minutos.',
  },
];

for (const card of cards) {
  await db.collection('theory').add(card);
  console.log(`✅ [${card.subject}] ${card.title}`);
}
console.log(`\n🎉 Seeded ${cards.length} theory cards!`);
